# Generated by Django 4.2.2 on 2023-07-02 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='supporting_docs',
            field=models.FileField(blank=True, upload_to='supdocfolder'),
        ),
    ]
