# Generated by Django 4.2.2 on 2023-07-04 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0002_alter_leaverequest_supporting_docs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
