# Generated by Django 4.2.2 on 2023-07-04 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0003_alter_registration_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='confirmPassword',
        ),
        migrations.AlterField(
            model_name='registration',
            name='email',
            field=models.CharField(max_length=35, unique=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
