# Generated by Django 4.2.2 on 2023-06-24 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hnum', models.CharField(max_length=3)),
                ('hname', models.CharField(max_length=30)),
                ('tname', models.CharField(max_length=10)),
            ],
        ),
    ]
