# Generated by Django 4.0.4 on 2023-06-28 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_timetable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='hnum',
            field=models.CharField(max_length=3, unique=True),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='tname',
            field=models.CharField(max_length=30),
        ),
    ]
