# Generated by Django 4.0.4 on 2023-06-28 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_timetable_hnum_alter_timetable_tname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='hnum',
            field=models.IntegerField(max_length=3, unique=True),
        ),
    ]
