# Generated by Django 4.0.4 on 2023-06-28 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_timetable_hnum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='hnum',
            field=models.IntegerField(unique=True),
        ),
    ]
