# Generated by Django 4.2.2 on 2023-07-02 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_csvdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CSVData',
        ),
    ]
