# Generated by Django 4.2.2 on 2023-07-06 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MusicFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('artist', models.CharField(max_length=50)),
                ('song', models.FileField(upload_to='media')),
            ],
            options={
                'db_table': 'MusicFiles',
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('confirmPassword', models.CharField(max_length=20)),
                ('insta', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_title', models.CharField(max_length=50)),
                ('s_artist', models.CharField(max_length=50)),
                ('songs', models.FileField(upload_to='songs')),
            ],
            options={
                'db_table': 'Songs',
            },
        ),
    ]
